USE [OutboxPatternDB]
GO
/****** Object:  Table [dbo].[CUSTOMER]    Script Date: 9/28/2023 1:22:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOMER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_NAME] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_CUSTOMER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CUSTOMER_ADDED_OUTBOX]    Script Date: 9/28/2023 1:22:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOMER_ADDED_OUTBOX](
	[EVENT_ID] [uniqueidentifier] NOT NULL,
	[EVENT_TYPE] [nvarchar](100) NOT NULL,
	[TIMESTAMP] [datetime] NOT NULL,
	[EVENT_STATUS] [int] NOT NULL,
	[EXCHANGE_NAME] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO
